Kaia/ServiceEntryPoint:
  Enabled: true
  Description: 'Service classes should only be called via .call'
  SafeAutoCorrect: false

Kaia/ServiceFileInheritance:
  Enabled: true
  Description: 'Classes defined in app/services must inherit from a "Service"-suffixed parent class.'
  SafeAutoCorrect: false

Kaia/ServiceFileSuffix:
  Enabled: true
  Description: 'Classes defined in app/services must have a "Service" suffix.'
  SafeAutoCorrect: false

Kaia/ServiceNoAddedClassMethods:
  Enabled: true
  Description: 'Service classes should not define class methods.'
  SafeAutoCorrect: false

Kaia/ServiceNoAddedPublicMethods:
  Enabled: true
  Description: 'Only the `call` method can be public in a Service.'
  SafeAutoCorrect: false

Kaia/ServiceSuffix:
  Enabled: true
  Description: 'Service classes should have a "Service" suffix.'
  SafeAutoCorrect: false

Kaia/UseMemoWise:
  Enabled: true
  Description: 'Use `memo_wise` instead of manually memoizing with instance variables.'
  SafeAutoCorrect: true
